application: {}
technology: {}
settings:
  manifests:
    paths:
      - "manifests"
  relationships:
    default-synthetic-label: "uses"
  views:
    path: "views"
  facets:
    globalEnabled: true
    directoryNameTemplate: "%s-%s"
styles:
  atomic:
    shadowing: false
  composite:
    shadowing: false
    background-color: "transparent"
    line-color: "darkgray"
    line-style: 5
    font-style: "normal"
formatters:
  atomic:
    name: "%s"
    qualifiers: "%s"
    description: "%s"
  composite:
    name: "%s"
    qualifiers: "%s"
  link:
    label: "%s"
    qualifiers: "%s"
