@startuml PaymentGateway_overview
title System - PaymentGateway - Overview
skinparam defaultTextAlignment center
skinparam defaultTextAlignment<<atomic>> center
skinparam wrapWidth 200
skinparam maxMessageSize 150
hide stereotype
<style>
.composite {
BackgroundColor: transparent
LineColor: darkgray
LineStyle: 5
FontStyle: normal
}
</style>
rectangle PaymentGateway <<system>> <<atomic>> [
PaymentGateway
[system]
]
rectangle EcommercePlatform <<solution>> <<atomic>> [
EcommercePlatform
[solution]
]
EcommercePlatform --> PaymentGateway
@enduml
