@startuml EcommercePlatform-ProductCatalog_deep
title System - ProductCatalog - Deep View
skinparam defaultTextAlignment center
skinparam defaultTextAlignment<<atomic>> center
skinparam wrapWidth 200
skinparam maxMessageSize 150
hide stereotype
<style>
.composite {
BackgroundColor: transparent
LineColor: darkgray
LineStyle: 5
FontStyle: normal
}
</style>
rectangle EcommercePlatform as "EcommercePlatform\n[solution]" <<composite>> {
rectangle EcommercePlatform.OrderProcessing <<system>> <<atomic>> [
OrderProcessing
[system]
]
rectangle EcommercePlatform.ProductCatalog <<system>> <<atomic>> [
ProductCatalog
[system]
]
rectangle EcommercePlatform.UserInterface <<system>> <<atomic>> [
UserInterface
[system]
]
}
EcommercePlatform.OrderProcessing --> EcommercePlatform.ProductCatalog
EcommercePlatform.UserInterface --> EcommercePlatform.ProductCatalog
@enduml
