@startuml EcommercePlatform.UserManagement.UserProfileDatabase_deep
title Container - UserProfileDatabase - Deep View
skinparam defaultTextAlignment center
skinparam defaultTextAlignment<<atomic>> center
skinparam wrapWidth 200
skinparam maxMessageSize 150
hide stereotype
<style>
.composite {
BackgroundColor: transparent
LineColor: darkgray
LineStyle: 5
FontStyle: normal
}
</style>
rectangle EcommercePlatform as "EcommercePlatform\n[solution]" <<composite>> {
rectangle EcommercePlatform.UserManagement as "UserManagement\n[system]" <<composite>> {
rectangle EcommercePlatform.UserManagement.UserProfileDatabase <<container>> <<atomic>> [
UserProfileDatabase
[container]
]
rectangle EcommercePlatform.UserManagement.UserProfileService <<container>> <<atomic>> [
UserProfileService
[container]
]
}
}
EcommercePlatform.UserManagement.UserProfileService --> EcommercePlatform.UserManagement.UserProfileDatabase
@enduml
