@startuml EcommercePlatform.UserManagement.IdentityAndAccessManagement_deep
title Container - IdentityAndAccessManagement - Deep View
skinparam defaultTextAlignment center
skinparam defaultTextAlignment<<atomic>> center
skinparam wrapWidth 200
skinparam maxMessageSize 150
hide stereotype
<style>
.composite {
BackgroundColor: transparent
LineColor: darkgray
LineStyle: 5
FontStyle: normal
}
</style>
rectangle EcommercePlatform as "EcommercePlatform\n[solution]" <<composite>> {
rectangle EcommercePlatform.UserManagement as "UserManagement\n[system]" <<composite>> {
rectangle EcommercePlatform.UserManagement.IdentityAndAccessManagement <<container>> <<atomic>> [
IdentityAndAccessManagement
[container]
]
rectangle EcommercePlatform.UserManagement.UserProfileService <<container>> <<atomic>> [
UserProfileService
[container]
]
}
}
rectangle SocialIdentityProvider <<system>> <<atomic>> [
SocialIdentityProvider
[system]
]
EcommercePlatform.UserManagement.IdentityAndAccessManagement --> EcommercePlatform.UserManagement.UserProfileService
EcommercePlatform.UserManagement.IdentityAndAccessManagement --> SocialIdentityProvider
@enduml
