@startuml EcommercePlatform.UserInterface_deep
title System - UserInterface - Deep View
skinparam defaultTextAlignment center
skinparam defaultTextAlignment<<atomic>> center
skinparam wrapWidth 200
skinparam maxMessageSize 150
hide stereotype
<style>
.composite {
BackgroundColor: transparent
LineColor: darkgray
LineStyle: 5
FontStyle: normal
}
</style>
person User <<atomic>> <<person>> [
User
[person]
]
rectangle EcommercePlatform as "EcommercePlatform\n[solution]" <<composite>> {
rectangle EcommercePlatform.OrderProcessing <<system>> <<atomic>> [
OrderProcessing
[system]
]
rectangle EcommercePlatform.ContentManagement <<system>> <<atomic>> [
ContentManagement
[system]
]
rectangle EcommercePlatform.ProductCatalog <<system>> <<atomic>> [
ProductCatalog
[system]
]
rectangle EcommercePlatform.UserManagement as "UserManagement\n[system]" <<composite>> {
rectangle EcommercePlatform.UserManagement.UserProfileService <<container>> <<atomic>> [
UserProfileService
[container]
]
}
rectangle EcommercePlatform.UserInterface <<system>> <<atomic>> [
UserInterface
[system]
]
}
EcommercePlatform.UserInterface --> EcommercePlatform.ContentManagement
EcommercePlatform.UserInterface --> EcommercePlatform.OrderProcessing
User --> EcommercePlatform.UserInterface
EcommercePlatform.UserInterface --> EcommercePlatform.UserManagement.UserProfileService
EcommercePlatform.UserInterface --> EcommercePlatform.ProductCatalog
@enduml
