@startuml User_deep
title Person - User - Deep View
skinparam defaultTextAlignment center
skinparam defaultTextAlignment<<atomic>> center
skinparam wrapWidth 200
skinparam maxMessageSize 150
hide stereotype
<style>
.composite {
BackgroundColor: transparent
LineColor: darkgray
LineStyle: 5
FontStyle: normal
}
</style>
person User <<atomic>> <<person>> [
User
[person]
]
rectangle EcommercePlatform as "EcommercePlatform\n[solution]" <<composite>> {
rectangle EcommercePlatform.UserInterface <<system>> <<atomic>> [
UserInterface
[system]
]
}
User --> EcommercePlatform.UserInterface
@enduml
