@startuml SocialIdentityProvider_overview
title System - SocialIdentityProvider - Overview
skinparam defaultTextAlignment center
skinparam defaultTextAlignment<<atomic>> center
skinparam wrapWidth 200
skinparam maxMessageSize 150
hide stereotype
<style>
.composite {
BackgroundColor: transparent
LineColor: darkgray
LineStyle: 5
FontStyle: normal
}
</style>
rectangle EcommercePlatform <<solution>> <<atomic>> [
EcommercePlatform
[solution]
]
rectangle SocialIdentityProvider <<system>> <<atomic>> [
SocialIdentityProvider
[system]
]
EcommercePlatform --> SocialIdentityProvider : uses
@enduml
