@startuml EcommercePlatform.UserManagement_detailed
title System - UserManagement - Detailed View
skinparam defaultTextAlignment center
skinparam defaultTextAlignment<<atomic>> center
skinparam wrapWidth 200
skinparam maxMessageSize 150
hide stereotype
<style>
.composite {
BackgroundColor: transparent
LineColor: darkgray
LineStyle: 5
FontStyle: normal
}
</style>
rectangle EcommercePlatform as "EcommercePlatform\n[solution]" <<composite>> {
rectangle EcommercePlatform.UserInterface <<system>> <<atomic>> [
UserInterface
[system]
]
rectangle EcommercePlatform.UserManagement as "UserManagement\n[system]" <<composite>> {
rectangle EcommercePlatform.UserManagement.IdentityAndAccessManagement <<container>> <<atomic>> [
IdentityAndAccessManagement
[container]
]
rectangle EcommercePlatform.UserManagement.UserProfileDatabase <<container>> <<atomic>> [
UserProfileDatabase
[container]
]
rectangle EcommercePlatform.UserManagement.UserProfileService <<container>> <<atomic>> [
UserProfileService
[container]
]
}
rectangle EcommercePlatform.UserManagement as "UserManagement\n[system]" <<composite>> {
rectangle EcommercePlatform.UserManagement.IdentityAndAccessManagement <<container>> <<atomic>> [
IdentityAndAccessManagement
[container]
]
rectangle EcommercePlatform.UserManagement.UserProfileService <<container>> <<atomic>> [
UserProfileService
[container]
]
}
}
rectangle SocialIdentityProvider <<system>> <<atomic>> [
SocialIdentityProvider
[system]
]
EcommercePlatform.UserInterface --> EcommercePlatform.UserManagement.UserProfileService
EcommercePlatform.UserManagement.IdentityAndAccessManagement --> EcommercePlatform.UserManagement.UserProfileService
EcommercePlatform.UserManagement.IdentityAndAccessManagement --> SocialIdentityProvider
EcommercePlatform.UserManagement.UserProfileService --> EcommercePlatform.UserManagement.UserProfileDatabase
@enduml
