@startuml EcommercePlatform_UserInterface-overview
title System - UserInterface - Overview
skinparam defaultTextAlignment center
skinparam defaultTextAlignment<<atomic>> center
skinparam wrapWidth 200
skinparam maxMessageSize 150
hide stereotype
<style>
.composite {
BackgroundColor: transparent
LineColor: darkgray
LineStyle: 5
FontStyle: normal
}
</style>
rectangle EcommercePlatform as "EcommercePlatform\n[solution]" <<composite>> {
rectangle EcommercePlatform.ContentManagement <<system>> <<atomic>> [
ContentManagement
[system]
]
rectangle EcommercePlatform.OrderProcessing <<system>> <<atomic>> [
OrderProcessing
[system]
]
rectangle EcommercePlatform.ProductCatalog <<system>> <<atomic>> [
ProductCatalog
[system]
]
rectangle EcommercePlatform.UserInterface <<system>> <<atomic>> [
UserInterface
[system]
]
rectangle EcommercePlatform.UserManagement <<system>> <<atomic>> [
UserManagement
[system]
]
}
person User <<atomic>> <<person>> [
User
[person]
]
EcommercePlatform.UserInterface --> EcommercePlatform.ContentManagement
EcommercePlatform.UserInterface --> EcommercePlatform.OrderProcessing
EcommercePlatform.UserInterface --> EcommercePlatform.ProductCatalog
EcommercePlatform.UserInterface --> EcommercePlatform.UserManagement : uses
User --> EcommercePlatform.UserInterface
@enduml
