name: Continuous Integration - Build

on: [ push, pull_request ]

jobs:
  Build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
        with:
          fetch-depth: 0
      - name: "Install apt dependencies"
        run: "sudo apt-get install -y graphviz wget curl"
      - name: "Cache SonarCloud packages"
        uses: "actions/cache@v3"
        with:
          path: "~/.sonar/cache"
          key: "${{ runner.os }}-sonar"
          restore-keys: "${{ runner.os }}-sonar"
      - name: "Set up JDK 17"
        uses: "actions/setup-java@v2"
        with:
          java-version: "17"
          distribution: "adopt"
          cache: maven
      - name: "Build artifacts"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./mvnw verify \
            org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            --batch-mode \
            --update-snapshots \
            -Dsonar.projectKey=tmorin_archicode \
            -Dsonar.java.coveragePlugin=jacoco \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/jacoco-report/jacoco.xml
      - name: "Publish snapshot artifacts"
        if: ${{ github.ref == 'refs/heads/main' && !startsWith(github.event.head_commit.message, 'chore(release)') }}
        run: |
          ./mvnw deploy \
            --batch-mode \
            -Dmaven.test.skip \
            -Dplugin.asciidoctor.skip=true \
            -Dquarkus.container-image.build=true \
            -Dquarkus.container-image.push=true \
            -Dquarkus.container-image.tag=latest
        env:
          QUARKUS_CONTAINER_IMAGE_USERNAME: ${{ github.actor }}
          QUARKUS_CONTAINER_IMAGE_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Publish release artifacts"
        if: ${{ startsWith(github.ref, 'refs/tags/') && startsWith(github.event.head_commit.message, 'chore(release)') }}
        run: |
          ./mvnw deploy \
            --batch-mode \
            -Dmaven.test.skip \
            -Dplugin.asciidoctor.skip=true \
            -Dquarkus.container-image.build=true \
            -Dquarkus.container-image.push=true
        env:
          QUARKUS_CONTAINER_IMAGE_USERNAME: ${{ github.actor }}
          QUARKUS_CONTAINER_IMAGE_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Publish website"
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: "peaceiris/actions-gh-pages@v3"
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "target/generated-docs"
